language: go
go:
  - 1.10

install:
  - wget https://github.com/bitnami/stacksmith-cli/releases/download/v0.1/stacksmith -O /tmp/stacksmith
  - install /tmp/stacksmith /usr/local/bin/stacksmith
  - stacksmith version

script:
  - go test -v ./...
  - go build -ldflags="-s -w"

deploy:
  - provider: script
  
    script:
      - stacksmith auth login --access-token $STACKSMITH_ACCESS_TOKEN
      - stacksmith build
    
    skip_cleanup: true
    on:
      branch: master
