language: go
go:
  - 1.10

before_script:
  - mkdir -p stacksmith-cli
  - wget https://github.com/bitnami/stacksmith-cli/releases/download/v0.1/stacksmith -O stacksmith-cli/stacksmith
  - chmod +x stacksmith-cli/stacksmith
  - export PATH=$PATH:$PWD/stacksmith-cli
  
  - stacksmith auth login --access-token $STACKSMITH_ACCESS_TOKEN

script:
  - go test -v ./...
  - go build
  - stacksmith build
